server:
  port: 8100

spring:
  application:
    name: project-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop



