server:
  port: 8101

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: roedeer.rmq.cloudamqp.com
    username: wnwjkwrv
    virtual-host: wnwjkwrv
    password: 7ECy4EkNoo20We1lk28-OMcx6bCyBWo4
    ssl:
      enabled: true
security:
  oauth2:
    client:
      client-id: oauth2
      client-secret: oauth2
    resource:
      token-info-uri: http://localhost:8200/oauth/check_token

auth-service:
  username: admin
  password: passw0rd