server:
  port: 8101

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
security:
  oauth2:
    client:
      client-id: oauth2
      client-secret: oauth2
    resource:
      token-info-uri: http://localhost:8200/oauth/check_token

auth-service:
  username: admin
  password: passw0rd