server:
  port: 8200

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: secret

user-service:
  username: admin
  password: passw0rd
