server:
  port: 8000
  tomcat:
    connection-timeout: 10000
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: zuul
    key-password: password
spring:
  application:
    name: gateway
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
zuul:
  prefix: /api
  routes:
    oauth2:
      path: /oauth/**
      service-id: auth-service
      strip-prefix: false
    projects:
      path: /projects/**
      service-id: project-service
      strip-prefix: false
    users:
      path: /**
      service-id: user-service
      strip-prefix: false

  sensitive-headers: Cookie, Set-Cookie