version: "3.1"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - psql:/var/lib/postgresql/data
  rabbit:
    image: rabbitmq:3.8.14-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

volumes:
  psql:
networks:
  rabbitmq_go_net:
    driver: bridge