version: "3.1"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - psql:/var/lib/postgresql/data
volumes:
  psql: